version: '3.8'

services: 
  db: 
    image: "postgres:14"
    ports:
      - "5432:5432"
    environment: 
      - PG_USER=postgres
      - PG_PW=postgres
      - PG_DB=todo
  node:
    image: node:latest
    command: node index.js
    ports:
      - "3001:3001"
    links:
      - db
    working_dir: /src
    environment:
      PG_DB: todo
      PG_USER: postgres
      PG_PW: postgres
      DATABASE_URL: postgres://username:postgres@db:5432/todo
    volumes:
      - ./:/src