version: "3.9"
services:
  app:
    build: .
    ports: 
      - 3001:3001
    env_file: .env
    depends_on: 
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: samuele2512
      POSTGRES_DB: todo
    ports: 
      - 5432:5432
    volumes: 
      - db-data:/var/lib/postgresql/data
volumes: 
  db-data:
  